language: node_js

node_js:
  - "9"

cache:
  yarn: true

before_script:
  - yarn install

script:
  - yarn lint
  - yarn test:ci
  - yarn build:gh-pages

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false"

notifications:
  email:
    on_failure: change
    on_success: change
