// Based on: https://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application

import * as fs from 'fs'
import * as moment from 'moment'
import * as child_process from 'child_process'
import { Observable } from 'rxjs/Observable'
import { combineLatest } from 'rxjs/observable/combineLatest'


const describe = new Observable<string>(s => {
  child_process.exec(
    'git describe --always',
    { encoding: 'buffer' },
    (error: Error, stdout: Buffer, stderr: Buffer) => {
      if (error !== null) {
        console.log('git error: ' + error + stderr)
      }
      s.next(stdout.toString().trim())
      s.complete()
  })
})

const branch = new Observable<string>(s => {
  child_process.exec(
    'git rev-parse --abbrev-ref HEAD',
    { encoding: 'buffer' },
    (error: Error, stdout: Buffer, stderr: Buffer) => {
      if (error !== null) {
        console.log('git error: ' + error + stderr)
      }
      s.next(stdout.toString().trim())
      s.complete()
  })
})

moment.locale('pt_br')

combineLatest(branch, describe)
  .subscribe(([current_branch, version]) => {
    console.log(`Version: ${version}, Branch: ${current_branch}, Package Version: ${process.env.npm_package_version}`)

    const content = '// this file is automatically generated by git.version.ts script\n' +
      `export const consts = {
  packageVersion: '${process.env.npm_package_version}',
  version: '${version}',
  branch: '${current_branch}',
  buildTime: '${moment().format('DD/MM/YYYY HH:mm')}',
}\n`

    fs.writeFileSync(
      'src/environments/consts.ts',
      content,
      {encoding: 'utf8'}
    )
  })
